### PR TITLE
limit report call

### PR DESCRIPTION
**Pull request by britt-mo**
## Description
Set query to repeat, but remain below lambda payload limit.

Loop will happen 4 times, on the 5th it will break out.

### How to test
Open the dashboard for `stateuser` and see it load. Create more reports and make sure it still loads. It is slow.

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

### CODE REVIEW

**Review by tblackwe — APPROVED** [review]

**Comment by ntsummers1** [comment]
This works but jeez, I just tried with 13 different programs to load and its sloooowwww. Is it slow for anyone else?

**Review by ntsummers1 — APPROVED** [review]

**Comment by ntsummers1** [comment]
@gmrabian At around 3.5 seconds, yeah

**Comment by gmrabian** [comment]
Gotcha. Not great, but manageable for now

**Comment by gmrabian** [comment]
Looks like with the limit set to 4 the payload is coming back about 5.1MB, so I think 4 is our query limit for now
24 reports, when they are new
seeing 2.62s load time

**Review by ntsummers1 — APPROVED** [review]

**Comment by gmrabian** [comment]
deployed branch: https://d3kjj5ucyusrk1.cloudfront.net

**Review by tblackwe — APPROVED** [review]

**Pull request merged**
