### PR TITLE
alter leave form button and last saved on mobile

### PR DESCRIPTION
**Pull request by scwambach**
## Description

kept the `Leave Form` on mobile, but altered it to a close button. and well and shortend the `Last Saved` text and removed the check mark on mobile

### How to test

Trigger a last saved event and shrink the screen

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

### CODE REVIEW

**Comment by britt-mo** [comment]
When I tested this, the 'last saved' text shows up the first time I open the program and the first time I enter the program after submitting, but disappears after those two scenarios.

**Comment by scwambach** [comment]
@britt-mo Yeah I ran into that as well, but that seems like a separate bug

**Comment by britt-mo** [comment]
> @britt-mo Yeah I ran into that as well, but that seems like a separate bug

Okay, other than that it looked correct/as you described.

**Review by britt-mo — APPROVED** [review]

**Review by gmrabian — APPROVED** [review]
I think `last saved` isn't showing up because we're kind of in a limbo between autosave and manual save. (It should show up anytime you've saved, which is why it shows up the first time and not again).
Anyway this PR is good lol

**Pull request merged**
