### PR TITLE
some fields should be ratios

### PR DESCRIPTION
**Pull request by braxex**
just do it

### CODE REVIEW

**Review by gmrabian — CHANGES_REQUESTED** [review]
First ratio adds the colon and lets you tab by (it does throw error on save)? Second one immediately throws. I believe there is another here (D1.X.8) that should be a ratio as well, no?


https://user-images.githubusercontent.com/57802560/199735876-f69bf544-3394-42fa-a341-0375a2e335a2.mov

**Comment by braxex** [comment]
@gmrabian Ready for review.

**Review by gmrabian — APPROVED** [review]
works great

**Review by BearHanded — APPROVED** [review]
lgtm

**Pull request merged**
