### PR TITLE
add Thomas

### PR DESCRIPTION
**Pull request by gmrabian**
## Description
Yay

### How to test
Thomas shows up in PR reviewers automatically (once merged and assuming Thomas is already added as a contributor in GitHub)

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

### CODE REVIEW

**Comment by gmrabian** [comment]
@braxex @TheDanMiller can we add Thomas to the contributors?

**Review by karla-vm — APPROVED** [review]

**Comment by braxex** [comment]
> @braxex @TheDanMiller can we add Thomas to the contributors?

@gmrabian Added

**Comment by braxex** [comment]
@gmrabian You have angered the code gods by including a capital letter in your branch name.

**Comment by gmrabian** [comment]
@braxex I somehow knew that would be a problem and did it anyway. Want to ram it in anyway, or open a new one?

**Comment by braxex** [comment]
> @braxex I somehow knew that would be a problem and did it anyway. Want to ram it in anyway, or open a new one?

@gmrabian Dealer's choice.

**Comment by gmrabian** [comment]
@braxex I honestly don't care if this deploys so I say we do it anyway. Feel free to approve and override

**Review by braxex — APPROVED** [review]

**Pull request merged**
