### PR TITLE
MDCT-93: Configure Jest testing

### PR DESCRIPTION
**Pull request by braxex**
# Description

The [ticket](https://qmacbis.atlassian.net/browse/MDCT-93) was just to set up Jest testing in the repo, which it turns out was already done thanks to QMR. There were a couple messed up tests, though, which I fixed the same way as in QMR.

The problem was the `createCompoundKey` function, which was treating `measures` as required and ignoring `coreset`, when it needed to treat `measures` as optional and require `coreset`. See also the last two tests in `services/app-api/handlers/dynamoUtils/tests/createCompoundKey.test.ts`.

## How to test

1. To run frontend tests: `cd services/ui-src && yarn && yarn test`
2. To run api tests: `cd services/app-api && yarn && yarn test`

## Dependencies

No updated dependencies.

# Get it done

1. You will review it (thanks!)
2. I will merge it (good job, me).

## Code authors checklist

- [x] I have performed a self-review of my code
- [x] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [x] ~~Necessary analytics were added, or no new analytics were required~~
- [x] ~~I have made corresponding changes to the documentation~~
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [x] I have done the deep review and verified the items in the above checklist are g2g
- [x] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

### CODE REVIEW

**Review by BearHanded — APPROVED** [review]
Ran locally and confirmed functionality

**Review by karla-vm — APPROVED** [review]
Looks good, I was able to run the tests on my end.

**Review by gmrabian — CHANGES_REQUESTED** [review]
I'm getting an error when I try to run jest

```
>> cd services/ui-src
>> yarn test
yarn run v1.22.17
warning package.json: No license field
$ jest --setupFiles dotenv/config
/bin/sh: jest: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>> cd ../app-api/
>> yarn test
yarn run v1.22.17
$ jest
/bin/sh: jest: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is there an additional step or install I need to run? Idk if something is implied here like yarn install

**Comment by gmrabian** [comment]
Thanks! Still learning this stuff. It works for me now :)

**Review by gmrabian — APPROVED** [review]

**Comment by braxex** [comment]
Please excuse the noise while I appease the pre-commit linter. 👷 🏗 🚧

**Pull request merged**
