### PR TITLE
MDCT-435: Section D: Quality Measures (dqm) Schema

### PR DESCRIPTION
**Pull request by karla-vm**
## Description

Closes a sub-task of [MDCT-435](https://qmacbis.atlassian.net/browse/MDCT-435).

This is the `formJson` and the schema for Section D: Quality Measures.

### How to test

N/A

### Changed Dependencies

N/A

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

### CODE REVIEW

**Comment by gmrabian** [comment]
This radio should have start and enddate fields, right? Only one showed up
Screen Shot 2022-09-08 at 10 17 46 AM

**Comment by gmrabian** [comment]
These fields are missing (screenshot from Jira ticket)
Screen Shot 2022-09-08 at 10 17 52 AM

**Comment by karla-vm** [comment]
**Note:** This form is not rendering within a Drawer, needs to be hooked up correctly later on.

**Review by gmrabian — APPROVED** [review]
💃  cha cha cha

**Pull request merged**
